version: '3.6'
services:
  postgres:
    image: postgres:13
    ports:
      # - '5932:5432' # expose pg on port 5932 to not collide with pg from elswhere
      - '5432:5432' # expose pg on port 5932 to not collide with pg from elswhere
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      # POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_PASSWORD: postgres
      # POSTGRES_HOST_AUTH_METHOD: trust

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - '8080:80'
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  db-data:
  pgadmin-data:
